<?php

/**
 * 微信配置
 */

namespace app\admin\controller;

use think\facade\View;
use think\facade\Lang;
use think\Validate;
use GatewayClient\Gateway;

/**
 * ============================================================================
 * DSO2O多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 控制器
 */
class O2oDistributor extends AdminControl {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        Lang::load(base_path() . 'admin/lang/' . config('lang.default_lang') . '/o2o_distributor.lang.php');
    }

    public function index() {
        $o2o_distributor_model = model('o2o_distributor');
        $condition = array();
        $search_field_value = input('search_field_value');
        $search_field_name = input('search_field_name');
        if ($search_field_value != '') {
            switch ($search_field_name) {
                case 'o2o_distributor_name':
                    $condition[]=array('o2o_distributor_name','like', '%' . trim($search_field_value) . '%');
                    break;
                case 'o2o_distributor_realname':
                    $condition[]=array('o2o_distributor_realname','like', '%' . trim($search_field_value) . '%');
                    break;
                case 'o2o_distributor_phone':
                    $condition[]=array('o2o_distributor_phone','like', '%' . trim($search_field_value) . '%');
                    break;
                case 'o2o_distributor_email':
                    $condition[]=array('o2o_distributor_email','like', '%' . trim($search_field_value) . '%');
                    break;
            }
        }
        $search_state = input('search_state');
        switch ($search_state) {
            case '1':
                $condition[]=array('o2o_distributor_state','=', '1');
                break;
            case '0':
                $condition[]=array('o2o_distributor_state','=', '0');
                break;
            case '2':
                $condition[]=array('o2o_distributor_state','=', '2');
                break;
            case '3':
                $condition[]=array('o2o_distributor_state','=', '3');
                break;
            default:
                if (input('verify')) {
                    $condition[]=array('o2o_distributor_state','in', array(2, 3));
                } else {
                    $condition[]=array('o2o_distributor_state','in', array(0, 1));
                }
                break;
        }
        $filtered = 0;
        if ($condition) {
            $filtered = 1;
        }
        $condition = array_merge($condition, array(
            array('store_id' ,'=', 0)
        ));
        $order = 'o2o_distributor_addtime desc';
        $o2o_distributor_list = $o2o_distributor_model->getO2oDistributorList($condition, '*', 10, $order);
        View::assign('o2o_distributor_list', $o2o_distributor_list);
        View::assign('show_page', $o2o_distributor_model->page_info->render());

        View::assign('search_field_name', trim($search_field_name));
        View::assign('search_field_value', trim($search_field_value));

        View::assign('filtered', $filtered); //是否有查询条件

        if (input('verify')) {
            $this->setAdminCurItem('verify');
        } else {
            $this->setAdminCurItem('index');
        }
        return View::fetch();
    }
    
    public function get_distributor_list(){
        $o2o_distributor_model = model('o2o_distributor');
        $order_model = model('order');
        $condition = array();
        $region_id=input('param.region_id');
        $keyword=input('param.keyword');
        if($region_id){
            $area_model=model('area');
            $ids=$area_model->getChildrenIDs($region_id);
            $ids[]=$region_id;
            $condition[]=array('o2o_distributor_region_id','in',$ids);
        }
        if($keyword){
            $condition[]=array('o2o_distributor_name|o2o_distributor_realname|o2o_distributor_phone|o2o_distributor_email','like','%'.$keyword.'%');
        }
        $condition = array_merge($condition, array(
            array('store_id' ,'=', 0),
            array('o2o_distributor_state','=','1')
        ));
        $order = 'o2o_distributor_addtime desc';
        $o2o_distributor_list = $o2o_distributor_model->getO2oDistributorList($condition, '*', 10, $order);
        if(config('ds_config.instant_message_open')){
            Gateway::$registerAddress = config('ds_config.instant_message_register_url');
        }
        foreach ($o2o_distributor_list as $key => $val) {
            $o2o_distributor_list[$key]['o2o_distributor_avatar'] = get_o2o_distributor_file($val['o2o_distributor_avatar'],'avatar');
            $o2o_distributor_list[$key]['count_wait'] = $order_model->getOrderCount(array(array('o2o_order_deliver_time', '>', strtotime(date('Y-m-d 0:0:0'))), array('o2o_distributor_id', '=', $val['o2o_distributor_id']), array('order_state', 'in', [ORDER_STATE_DELIVER, ORDER_STATE_SEND])));
            $o2o_distributor_list[$key]['count_complete'] = $order_model->getOrderCount(array(array('o2o_order_deliver_time', '>', strtotime(date('Y-m-d 0:0:0'))), array('o2o_distributor_id', '=', $val['o2o_distributor_id']), array('order_state', 'in', [ORDER_STATE_SUCCESS])));
            $state=0;
            if(config('ds_config.instant_message_open')){
                if(Gateway::isUidOnline('5:'.$val['o2o_distributor_id'])){
                    $state=1;
                }
            }
            $o2o_distributor_list[$key]['state'] = $state;
        }
        ds_json_encode(10000, '', $o2o_distributor_list);
    }
    
    public function join(){
        session('name');
        $client_id = input('param.client_id');
        if (config('ds_config.instant_message_open')) {
            // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值(ip不能是0.0.0.0)
            try {
                Gateway::$registerAddress = config('ds_config.instant_message_register_url');
                // 加入某个群组（可调用多次加入多个群组）
                Gateway::joinGroup($client_id, 'seller');
            } catch (\Exception $e) {
                ds_json_encode(10001, $e->getMessage());
            }
        }
        ds_json_encode(10000, '');
    }

    public function map(){
        View::assign('baidu_ak', config('ds_config.baidu_ak'));
        $this->setAdminCurItem('map');
        return View::fetch();
    }
    
    public function add() {
        if (!request()->isPost()) {
            $this->setAdminCurItem('add');
            return View::fetch('form');
        } else {
            $o2o_distributor_model = model('o2o_distributor');
            $data = $this->post_data();

            $validate_data = array(
                'o2o_distributor_state' => input('post.o2o_distributor_state'),
                'o2o_distributor_realname' => input('post.o2o_distributor_realname'),
                'o2o_distributor_name' => input('post.o2o_distributor_name'),
                'o2o_distributor_password' => input('post.o2o_distributor_password'),
                'o2o_distributor_phone' => input('post.o2o_distributor_phone'),
                'o2o_distributor_email' => input('post.o2o_distributor_email'),
                'o2o_distributor_region_id' => intval(input('post.o2o_distributor_region_id')),
                'o2o_distributor_region_name' => input('post.o2o_distributor_region_name'),
                'o2o_distributor_errand_deposit' => input('post.o2o_distributor_errand_deposit'),
            );
            $o2o_distributor_validate = ds_validate('o2o_distributor');
            if (!$o2o_distributor_validate->scene('o2o_distributor_register')->check($validate_data)) {
                $this->error($o2o_distributor_validate->getError());
            }

            $condition[]=array('o2o_distributor_name','=',$data['o2o_distributor_name']);
            $result = $o2o_distributor_model->getO2oDistributorInfo($condition);
            if ($result) {
                $this->error(lang('o2o_distributor_name_remote'));
            }
            $result = $o2o_distributor_model->addO2oDistributor($data);
            if ($result) {
                $this->log(lang('ds_add') . lang('o2o_distributor') . '[' . $data['o2o_distributor_name'] . ']', 1);
                dsLayerOpenSuccess(lang('ds_common_save_succ'));
            } else {
                $this->error(lang('ds_common_save_fail'));
            }
        }
    }

    public function notice() {
        $id = intval(input('param.id'));
        if (!$id) {
            $this->error(lang('param_error'));
        }
        $o2o_distributor_model = model('o2o_distributor');
        $o2o_distributor_array = $o2o_distributor_model->getO2oDistributorInfo(array('o2o_distributor_id' => $id, 'store_id' => 0));
        if (!$o2o_distributor_array) {
            $this->error(lang('o2o_distributor_empty'));
        }
        if (!request()->isPost()) {
            return View::fetch('notice');
        } else {
            $content = input('param.content');
            if (!$content) {
                $this->error('请填写信息');
            }
            $o2o_distributor_notice_model = model('o2o_distributor_notice');
            $o2o_distributor_notice_model->addO2oDistributorNotice(array(
                'o2o_distributor_id' => $o2o_distributor_array['o2o_distributor_id'],
                'o2o_distributor_name' => $o2o_distributor_array['o2o_distributor_name'],
                'o2o_distributor_notice_type' => 0,
                'order_id' => 0,
                'o2o_distributor_notice_title' => '平台通知',
                'o2o_distributor_notice_content' => $content,
                'o2o_distributor_notice_add_time' => TIMESTAMP,
            ));
            dsLayerOpenSuccess('发送成功', url('O2oDistributor/index', ['verify' => in_array($o2o_distributor_array['o2o_distributor_state'], array(2, 3))]));
        }
    }

    public function edit() {
        $id = intval(input('param.id'));
        if (!$id) {
            $this->error(lang('param_error'));
        }
        $o2o_distributor_model = model('o2o_distributor');
        $o2o_distributor_array = $o2o_distributor_model->getO2oDistributorInfo(array('o2o_distributor_id' => $id, 'store_id' => 0));
        if (!$o2o_distributor_array) {
            $this->error(lang('o2o_distributor_empty'));
        }
        if (!request()->isPost()) {
            View::assign('o2o_distributor_array', $o2o_distributor_array);
            return View::fetch('form');
        } else {

            $data = $this->post_data();

            $validate_data = array(
                'o2o_distributor_realname' => input('post.o2o_distributor_realname'),
                'o2o_distributor_password' => input('post.o2o_distributor_password'),
                'o2o_distributor_phone' => input('post.o2o_distributor_phone'),
                'o2o_distributor_email' => input('post.o2o_distributor_email'),
                'o2o_distributor_region_id' => intval(input('post.o2o_distributor_region_id')),
                'o2o_distributor_region_name' => input('post.o2o_distributor_region_name'),
                'o2o_distributor_errand_deposit' => input('post.o2o_distributor_errand_deposit'),
            );
            $o2o_distributor_validate = ds_validate('o2o_distributor');
            if (!$o2o_distributor_validate->scene('o2o_distributor_edit')->check($validate_data)) {
                $this->error($o2o_distributor_validate->getError());
            }

            if (isset($data['o2o_distributor_avatar']) && $o2o_distributor_array['o2o_distributor_avatar']) {
                @unlink(BASE_UPLOAD_PATH . DIRECTORY_SEPARATOR . ATTACH_O2O_DISTRIBUTOR . DIRECTORY_SEPARATOR . $o2o_distributor_array['o2o_distributor_avatar']);
            }
            $result = $o2o_distributor_model->editO2oDistributor($data, array('o2o_distributor_id' => $id, 'store_id' => 0));
            if ($result) {
                $this->log(lang('ds_edit') . lang('o2o_distributor') . '[' . $o2o_distributor_array['o2o_distributor_name'] . ']', 1);
                $content = input('param.content');
                if ($content) {
                    $o2o_distributor_notice_model = model('o2o_distributor_notice');
                    $o2o_distributor_notice_model->addO2oDistributorNotice(array(
                        'o2o_distributor_id' => $o2o_distributor_array['o2o_distributor_id'],
                        'o2o_distributor_name' => $o2o_distributor_array['o2o_distributor_name'],
                        'o2o_distributor_notice_type' => 0,
                        'order_id' => 0,
                        'o2o_distributor_notice_title' => '平台通知',
                        'o2o_distributor_notice_content' => $content,
                        'o2o_distributor_notice_add_time' => TIMESTAMP,
                    ));
                }
                dsLayerOpenSuccess(lang('ds_common_save_succ'), url('O2oDistributor/index', ['verify' => in_array($o2o_distributor_array['o2o_distributor_state'], array(2, 3))]));
            } else {
                $this->error(lang('ds_common_save_fail'));
            }
        }
    }

    public function del() {
        $id = intval(input('param.id'));
        if (!$id) {
            ds_json_encode(10001, lang('param_error'));
        }
        $o2o_distributor_model = model('o2o_distributor');
        $o2o_distributor_array = $o2o_distributor_model->getO2oDistributorInfo(array('o2o_distributor_id' => $id, 'store_id' => 0));
        if (!$o2o_distributor_array) {
            ds_json_encode(10001, lang('o2o_distributor_empty'));
        }
        //如果有正在配送的订单则不能删除
        $order_model=model('order');
        $o2o_errand_order_model=model('o2o_errand_order');
        if($order_model->getOrderCount(array(array('o2o_distributor_id','=',$id),array('order_state','in',array(ORDER_STATE_DELIVER,ORDER_STATE_SEND)))) || $o2o_errand_order_model->getO2oErrandOrderCount(array(array('o2o_distributor_id','=',$id),array('o2o_errand_order_state','in',array(ORDER_STATE_DELIVER,ORDER_STATE_SEND))))){
            ds_json_encode(10001, '该配送员有未完成的订单');
        }
        $result = $o2o_distributor_model->delO2oDistributorInfo(array('o2o_distributor_id' => $id, 'store_id' => 0), array($o2o_distributor_array));
        if (!$result) {
            ds_json_encode(10001, lang('ds_common_del_fail'));
        } else {
            $this->log(lang('ds_del') . lang('o2o_distributor') . '[' . $o2o_distributor_array['o2o_distributor_name'] . ']', 1);
            ds_json_encode(10000, lang('ds_common_del_succ'));
        }
    }

    public function post_data() {
        $data = array(
            'o2o_distributor_realname' => input('post.o2o_distributor_realname'),
            'store_id' => 0,
            'o2o_distributor_phone' => input('post.o2o_distributor_phone'),
            'o2o_distributor_email' => input('post.o2o_distributor_email'),
            'o2o_distributor_remark' => input('post.o2o_distributor_remark'),
            'o2o_distributor_introduce' => input('post.o2o_distributor_introduce'),
            'o2o_distributor_state' => intval(input('post.o2o_distributor_state')),
            'o2o_distributor_region_id' => intval(input('post.o2o_distributor_region_id')),
            'o2o_distributor_region_name' => input('post.o2o_distributor_region_name'),
            'o2o_distributor_errand_deposit' => input('post.o2o_distributor_errand_deposit'),
        );
        if (request()->action() == 'add') {
            $data['o2o_distributor_name'] = input('post.o2o_distributor_name');
            $data['o2o_distributor_addtime'] = TIMESTAMP;
        }
        if (input('post.o2o_distributor_password')) {
            $data['o2o_distributor_password'] = md5(input('post.o2o_distributor_password'));
        }
        //头像
        if (!empty($_FILES['_pic']['name'])) {
                $res=ds_upload_pic(ATTACH_O2O_DISTRIBUTOR,'_pic');
                if($res['code']){
                    $file_name=$res['data']['file_name'];
                    $data['o2o_distributor_avatar'] = $file_name;
                }else{
                    $this->error($res['msg']);
                }
                

        }


        return $data;
    }

    public function ajax() {
        $o2o_distributor_model = model('o2o_distributor');
        switch (input('param.branch')) {
            /**
             * 品牌名称
             */
            case 'o2o_distributor_name':
                /**
                 * 判断是否有重复
                 */
                $condition[]=array('o2o_distributor_name','=',trim(input('param.value')));
                $condition[]=array('o2o_distributor_id','<>',intval(input('param.id')));
                $result = $o2o_distributor_model->getO2oDistributorInfo($condition);
                if (empty($result)) {
                    echo 'true';
                    exit;
                } else {
                    echo 'false';
                    exit;
                }
                break;
        }
    }

    protected function getAdminItemList() {
        $menu_array = array(
            array(
                'name' => 'index',
                'text' => lang('ds_list'),
                'url' => url('O2oDistributor/index')
            ),
            array(
                'name' => 'verify',
                'text' => lang('ds_verify'),
                'url' => url('O2oDistributor/index', ['verify' => 1])
            ),
            array(
                'name' => 'add',
                'text' => lang('ds_add'),
                'url' => "javascript:dsLayerOpen('" . url('O2oDistributor/add') . "','添加配送员')"
            ),
            array(
                'name' => 'map',
                'text' => '地图',
                'url' => "javascript:dsLayerOpen('" . url('O2oDistributor/map') . "','配送员位置','1000px','843px')"
            ),
        );
        return $menu_array;
    }

}
