<?php

/**
 * 微信配置
 */
namespace app\admin\controller;
use think\facade\View;
use think\facade\Lang;
use think\Validate;
/**
 * ============================================================================
 * DSO2O多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 控制器
 */
class  O2oPrinter extends AdminControl {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        Lang::load(base_path() . 'admin/lang/'.config('lang.default_lang').'/o2o_printer.lang.php');
    }

    public function setting() {
        $config_model = model('config');
        if (!request()->isPost()) {
            $list_config = rkcache('config', true);
            View::assign('list_config', $list_config);
            return View::fetch();
        } else {
            $update_array['yly_open'] = intval(input('post.yly_open'));
            $update_array['yly_client_id'] = input('post.yly_client_id');
            $update_array['yly_client_secret'] = input('post.yly_client_secret');
            $result = $config_model->editConfig($update_array);
            if ($result) {
                dkcache('config');
                $this->log(lang('ds_edit').lang('o2o_printer_setting'),1);
                $this->success(lang('ds_common_save_succ'), 'O2oPrinter/setting');
            }else{
                $this->log(lang('ds_edit').lang('o2o_printer_setting'),0);
            }
        }
    }

    

}
